# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: USTC-UAV
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We are USTC-UAV
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://USTC-UAV.github.io" # the base hostname & protocol for your site
# twitter_username: USTC-UAV.github.io
github_username: USTC-UAV
disqus_shortname: USTC-UAV
# Build settings
markdown: kramdown
