# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown

# SEO settings
title: Julia中文社区 
description: "Julia中文社区"
keywords: "Julia,中文,China"

# Site settings
url: http://ustc-uav.github.io/

# baseurl: ""

# Author settings
author:
  name      : Julia Chinese Community
  github    : http://github.com/JuliaCN

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/dotX

# comments
# disqus_shortname: "fernandomoreira"
